projectId: app-4MTEELBK2qZ2GuBauQ6yhR
appName: testprj
description: This a test project
version: "1.0"
hostName: example.test
clusterURL: default
clusterIPs:
- 190.89.89.0
monitoring: true
microservices:
  CartService:
    serviceName: cartservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: werwer
    containerPort: 2121
  OrderService:
    serviceName: orderservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: wewe
    containerPort: 1211
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
  UserService:
    serviceName: userservice
    avgReplicas: 1
    minReplicas: 1
    maxReplicas: 1
    dockerImage: wewewe
    containerPort: 1211
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - CartService
  - OrderService
  - UserService
